image:
  file: .gitpod.Dockerfile 

# https://www.gitpod.io/docs/44_config_start_tasks/
# Fresh Workspace   before && init && command
# Restart Workspace before && command
# Snapshot          before && command
# Prebuild          before && init && prebuild
tasks:
  - command: R
    name: R Console
  - openMode: split-right
    command: echo SplitTerminal    
  - openIn: left
    command: echo LeftPanelTerminal

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: false
    addComment: true
    addBadge: false
    addLabel: false
