# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

std_rcpp <- function(data, na_rm = FALSE) {
    .Call(`_tsmp_std_rcpp`, data, na_rm)
}

list_to_matrix <- function(x) {
    .Call(`_tsmp_list_to_matrix`, x)
}

diff_lag <- function(x, lag = 1L) {
    .Call(`_tsmp_diff_lag`, x, lag)
}

diff2_lag <- function(x, lag = 1L, v = 0.0) {
    .Call(`_tsmp_diff2_lag`, x, lag, v)
}

fast_movsd_rcpp <- function(data, window_size) {
    .Call(`_tsmp_fast_movsd_rcpp`, data, window_size)
}

fast_avg_sd_rcpp <- function(data, window_size) {
    .Call(`_tsmp_fast_avg_sd_rcpp`, data, window_size)
}

mode_rcpp <- function(x) {
    .Call(`_tsmp_mode_rcpp`, x)
}

znorm_rcpp <- function(data) {
    .Call(`_tsmp_znorm_rcpp`, data)
}

binary_split_rcpp <- function(n) {
    .Call(`_tsmp_binary_split_rcpp`, n)
}

inner_product <- function(a, b) {
    .Call(`_tsmp_inner_product`, a, b)
}

sum_of_squares <- function(a) {
    .Call(`_tsmp_sum_of_squares`, a)
}

mpx_rcpp <- function(a, w, minlag, idxs = FALSE, euclidean = TRUE) {
    .Call(`_tsmp_mpx_rcpp`, a, w, minlag, idxs, euclidean)
}

mpxab_rcpp <- function(a, b, w, idxs = FALSE, euclidean = TRUE) {
    .Call(`_tsmp_mpxab_rcpp`, a, b, w, idxs, euclidean)
}

mpx_rcpp_parallel <- function(a, w, minlag, idxs = FALSE, euclidean = TRUE) {
    .Call(`_tsmp_mpx_rcpp_parallel`, a, w, minlag, idxs, euclidean)
}

mpxab_rcpp_parallel <- function(a, b, w, idxs = FALSE, euclidean = TRUE) {
    .Call(`_tsmp_mpxab_rcpp_parallel`, a, b, w, idxs, euclidean)
}

movmin <- function(data, window_size) {
    .Call(`_tsmp_movmin`, data, window_size)
}

movmax <- function(data, window_size) {
    .Call(`_tsmp_movmax`, data, window_size)
}

