# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

std_rcpp <- function(data, na_rm = FALSE) {
    .Call(`_tsmp_std_rcpp`, data, na_rm)
}

mode_rcpp <- function(x) {
    .Call(`_tsmp_mode_rcpp`, x)
}

znorm_rcpp <- function(data) {
    .Call(`_tsmp_znorm_rcpp`, data)
}

movmin <- function(data, window_size) {
    .Call(`_tsmp_movmin`, data, window_size)
}

movmax <- function(data, window_size) {
    .Call(`_tsmp_movmax`, data, window_size)
}

